
extra-source-files:
  - stack.yaml
  - README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text
  - network-uri

library:
  source-dirs: src
  dependencies:
    - bytestring
    - base64-bytestring
    - containers
    - optparse-applicative
  exposed-modules:
    - Console

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - test
      - bytestring
      - base64-bytestring
      - hspec
      - lens
      - containers

executables:
  test:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - test
      - giphy-api >= 0.6.0.0
      - optparse-applicative
      - optparse-text
      - bytestring
      - lens
      - wreq
      - transformers
      - errors
    other-modules:
      - Paths_test
